// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/v1/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c15b69877c1b4d97, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SignUpRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c15b69877c1b4d97, []int{1}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignUpResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c15b69877c1b4d97, []int{2}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SignUpResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*SignUpRequest)(nil), "SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "SignUpResponse")
}

func init() {
	proto.RegisterFile("protos/v1/user/user.proto", fileDescriptor_c15b69877c1b4d97)
}

var fileDescriptor_c15b69877c1b4d97 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0xa9, 0xa4, 0xb5, 0x4e, 0xb1, 0xc2, 0xe0, 0x21, 0xa9, 0x17, 0xc9, 0x49, 0x0f, 0x26,
	0x5a, 0x2f, 0x9e, 0x45, 0xfc, 0x01, 0x5b, 0x7a, 0xf1, 0xb6, 0xae, 0xc3, 0x12, 0x70, 0x3f, 0xdc,
	0x69, 0xea, 0xdf, 0x97, 0x9d, 0x26, 0x42, 0x2e, 0xcb, 0x3e, 0xef, 0xb2, 0xcf, 0x3b, 0x0c, 0x54,
	0x31, 0x85, 0x43, 0xe0, 0xf6, 0xf8, 0xd4, 0xf6, 0x4c, 0x49, 0x8e, 0x46, 0xb2, 0xfa, 0x11, 0x8a,
	0x3d, 0x53, 0x42, 0x84, 0xc2, 0x6b, 0x47, 0xe5, 0xec, 0x76, 0x76, 0x77, 0xa1, 0xe4, 0x8e, 0xd7,
	0x30, 0x27, 0xa7, 0xbb, 0xef, 0xf2, 0x4c, 0xc2, 0x13, 0xd4, 0xef, 0x70, 0xb9, 0xeb, 0xac, 0xdf,
	0x47, 0x45, 0x3f, 0x3d, 0xf1, 0x01, 0x2b, 0x28, 0xb2, 0x50, 0xbe, 0xae, 0xb6, 0xf3, 0x26, 0xfb,
	0x94, 0x44, 0xb8, 0x81, 0x65, 0xd4, 0xcc, 0xbf, 0x21, 0x7d, 0x0d, 0x92, 0x7f, 0xae, 0xdf, 0x60,
	0x3d, 0x7a, 0x38, 0x06, 0xcf, 0x84, 0x25, 0x9c, 0x73, 0x6f, 0x0c, 0x31, 0x8b, 0x6b, 0xa9, 0x46,
	0xcc, 0x2f, 0x8e, 0x98, 0xb5, 0xa5, 0x41, 0x33, 0xe2, 0xf6, 0x05, 0x56, 0xb9, 0x6f, 0x47, 0xe9,
	0xd8, 0x19, 0xc2, 0x7b, 0x58, 0x9c, 0xa4, 0xb8, 0x6e, 0x26, 0x53, 0x6e, 0xae, 0x9a, 0x69, 0xdb,
	0xeb, 0xcd, 0x47, 0x65, 0x53, 0x34, 0x0f, 0x2e, 0x78, 0x1b, 0xda, 0xe9, 0x86, 0x3e, 0x17, 0xc2,
	0xcf, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xa5, 0x5a, 0x82, 0x3a, 0x01, 0x00, 0x00,
}
