// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/v1/post/post.proto

package post

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PostMessage struct {
	PostId               string   `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Tags                 []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostMessage) Reset()         { *m = PostMessage{} }
func (m *PostMessage) String() string { return proto.CompactTextString(m) }
func (*PostMessage) ProtoMessage()    {}
func (*PostMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0049fa7b15cbaa87, []int{0}
}

func (m *PostMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMessage.Unmarshal(m, b)
}
func (m *PostMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMessage.Marshal(b, m, deterministic)
}
func (m *PostMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMessage.Merge(m, src)
}
func (m *PostMessage) XXX_Size() int {
	return xxx_messageInfo_PostMessage.Size(m)
}
func (m *PostMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PostMessage proto.InternalMessageInfo

func (m *PostMessage) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *PostMessage) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *PostMessage) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *PostMessage) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ListPostsByUserIdRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsByUserIdRequest) Reset()         { *m = ListPostsByUserIdRequest{} }
func (m *ListPostsByUserIdRequest) String() string { return proto.CompactTextString(m) }
func (*ListPostsByUserIdRequest) ProtoMessage()    {}
func (*ListPostsByUserIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0049fa7b15cbaa87, []int{1}
}

func (m *ListPostsByUserIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsByUserIdRequest.Unmarshal(m, b)
}
func (m *ListPostsByUserIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsByUserIdRequest.Marshal(b, m, deterministic)
}
func (m *ListPostsByUserIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsByUserIdRequest.Merge(m, src)
}
func (m *ListPostsByUserIdRequest) XXX_Size() int {
	return xxx_messageInfo_ListPostsByUserIdRequest.Size(m)
}
func (m *ListPostsByUserIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsByUserIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsByUserIdRequest proto.InternalMessageInfo

func (m *ListPostsByUserIdRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListPostsByUserIdResponse struct {
	PostMessages         []*PostMessage `protobuf:"bytes,1,rep,name=post_messages,json=postMessages,proto3" json:"post_messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListPostsByUserIdResponse) Reset()         { *m = ListPostsByUserIdResponse{} }
func (m *ListPostsByUserIdResponse) String() string { return proto.CompactTextString(m) }
func (*ListPostsByUserIdResponse) ProtoMessage()    {}
func (*ListPostsByUserIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0049fa7b15cbaa87, []int{2}
}

func (m *ListPostsByUserIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsByUserIdResponse.Unmarshal(m, b)
}
func (m *ListPostsByUserIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsByUserIdResponse.Marshal(b, m, deterministic)
}
func (m *ListPostsByUserIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsByUserIdResponse.Merge(m, src)
}
func (m *ListPostsByUserIdResponse) XXX_Size() int {
	return xxx_messageInfo_ListPostsByUserIdResponse.Size(m)
}
func (m *ListPostsByUserIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsByUserIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsByUserIdResponse proto.InternalMessageInfo

func (m *ListPostsByUserIdResponse) GetPostMessages() []*PostMessage {
	if m != nil {
		return m.PostMessages
	}
	return nil
}

type ListPostsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsRequest) Reset()         { *m = ListPostsRequest{} }
func (m *ListPostsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPostsRequest) ProtoMessage()    {}
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0049fa7b15cbaa87, []int{3}
}

func (m *ListPostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsRequest.Unmarshal(m, b)
}
func (m *ListPostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsRequest.Marshal(b, m, deterministic)
}
func (m *ListPostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsRequest.Merge(m, src)
}
func (m *ListPostsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPostsRequest.Size(m)
}
func (m *ListPostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsRequest proto.InternalMessageInfo

type ListPostsResponse struct {
	PostMessages         []*PostMessage `protobuf:"bytes,1,rep,name=post_messages,json=postMessages,proto3" json:"post_messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListPostsResponse) Reset()         { *m = ListPostsResponse{} }
func (m *ListPostsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPostsResponse) ProtoMessage()    {}
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0049fa7b15cbaa87, []int{4}
}

func (m *ListPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsResponse.Unmarshal(m, b)
}
func (m *ListPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsResponse.Marshal(b, m, deterministic)
}
func (m *ListPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsResponse.Merge(m, src)
}
func (m *ListPostsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPostsResponse.Size(m)
}
func (m *ListPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsResponse proto.InternalMessageInfo

func (m *ListPostsResponse) GetPostMessages() []*PostMessage {
	if m != nil {
		return m.PostMessages
	}
	return nil
}

func init() {
	proto.RegisterType((*PostMessage)(nil), "v1.post.PostMessage")
	proto.RegisterType((*ListPostsByUserIdRequest)(nil), "v1.post.ListPostsByUserIdRequest")
	proto.RegisterType((*ListPostsByUserIdResponse)(nil), "v1.post.ListPostsByUserIdResponse")
	proto.RegisterType((*ListPostsRequest)(nil), "v1.post.ListPostsRequest")
	proto.RegisterType((*ListPostsResponse)(nil), "v1.post.ListPostsResponse")
}

func init() {
	proto.RegisterFile("protos/v1/post/post.proto", fileDescriptor_0049fa7b15cbaa87)
}

var fileDescriptor_0049fa7b15cbaa87 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x4d, 0x4b, 0xf3, 0x40,
	0x14, 0x85, 0xc9, 0xdb, 0x2f, 0x7a, 0xfb, 0x0a, 0x3a, 0x14, 0x9d, 0x76, 0x55, 0x67, 0xd5, 0x8d,
	0x49, 0x3f, 0x04, 0x71, 0xdb, 0x8d, 0x14, 0xaa, 0x48, 0x44, 0x17, 0xdd, 0x48, 0x62, 0x86, 0x34,
	0x60, 0x32, 0x31, 0x77, 0xa6, 0x12, 0xf0, 0xf7, 0xf8, 0x3b, 0x65, 0x26, 0x69, 0x8c, 0x58, 0xdd,
	0xb8, 0x09, 0x73, 0x9e, 0x9b, 0x7b, 0x72, 0x4e, 0x18, 0x18, 0xa4, 0x99, 0x90, 0x02, 0x9d, 0xed,
	0xd4, 0x49, 0x05, 0x4a, 0xf3, 0xb0, 0x0d, 0x23, 0x9d, 0xed, 0xd4, 0xd6, 0x92, 0xbd, 0x41, 0xef,
	0x56, 0xa0, 0xbc, 0xe6, 0x88, 0x5e, 0xc8, 0xc9, 0x09, 0x74, 0x34, 0x7e, 0x8c, 0x02, 0x6a, 0x8d,
	0xac, 0x71, 0xd7, 0x6d, 0x6b, 0xb9, 0x0c, 0xc8, 0x31, 0xb4, 0x3d, 0x25, 0x37, 0x22, 0xa3, 0xff,
	0x0a, 0x5e, 0x28, 0xd2, 0x87, 0x96, 0x8c, 0xe4, 0x33, 0xa7, 0x0d, 0x83, 0x0b, 0x41, 0x08, 0x34,
	0x7d, 0x11, 0xe4, 0xb4, 0x69, 0xa0, 0x39, 0x6b, 0x26, 0xbd, 0x10, 0x69, 0x6b, 0xd4, 0xd0, 0x4c,
	0x9f, 0xd9, 0x1c, 0xe8, 0x2a, 0x42, 0xa9, 0x13, 0xe0, 0x22, 0xbf, 0x47, 0x9e, 0x2d, 0x03, 0x97,
	0xbf, 0x28, 0x8e, 0x52, 0x47, 0x51, 0xc8, 0xb3, 0x5a, 0x14, 0x65, 0xe6, 0xec, 0x01, 0x06, 0x7b,
	0x96, 0x30, 0x15, 0x09, 0x72, 0x72, 0x09, 0x07, 0xa6, 0x40, 0x5c, 0x14, 0x42, 0x6a, 0x8d, 0x1a,
	0xe3, 0xde, 0xac, 0x6f, 0x97, 0x85, 0xed, 0x5a, 0x5b, 0xf7, 0x7f, 0xfa, 0x29, 0x90, 0x11, 0x38,
	0xac, 0x7c, 0xcb, 0x10, 0xec, 0x06, 0x8e, 0x6a, 0xec, 0xcf, 0xdf, 0x98, 0xbd, 0x5b, 0xd0, 0xd4,
	0x53, 0xb2, 0xae, 0x19, 0xef, 0x4a, 0x90, 0xd3, 0xca, 0xe1, 0xa7, 0xbf, 0x32, 0x64, 0xbf, 0xbd,
	0x52, 0xe6, 0x5b, 0x40, 0xb7, 0x1a, 0x92, 0xc1, 0xf7, 0x85, 0x9d, 0xd7, 0x70, 0xdf, 0xa8, 0xf0,
	0x58, 0xcc, 0xd7, 0xd3, 0x30, 0x92, 0x1b, 0xe5, 0xdb, 0x4f, 0x22, 0x76, 0xf2, 0xf8, 0x75, 0x72,
	0x3e, 0xb9, 0x70, 0xae, 0xc4, 0xca, 0x4b, 0xc2, 0xb3, 0x3b, 0xa9, 0x82, 0x3c, 0x4a, 0x42, 0xe7,
	0xeb, 0x05, 0xf3, 0xdb, 0x46, 0xcf, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xda, 0xc3, 0xfa, 0x02,
	0x79, 0x02, 0x00, 0x00,
}
